6주차 코드 리뷰 제출
kakao-tech-campus-2nd-step3/Team11_FE pull request #45
Opened 2024-10-11 14:34 UTC by JaeanHan

## 📖️ 6주차 코드 리뷰 제출

##### 반영 브랜치 : `Master -> Review`

### ️️ 📝 설명
    6주차 코드 리뷰를 위해 작업물을 제출합니다!
    이번 주차에서 거의 모든 페이지 디자인을 수정하게 되어 코드 작업을 많이 하지 못했습니다..😢

2024-10-14 08:59 UTC, danmin20 requested changes
코드 로직이 크게 바뀐 부분들은 없어서 리뷰는 이 정도로 하겠습니다 ㅎㅎ 수고하셨습니다~

2024-10-14 08:59 UTC, danmin20 commented on src/components/CommunitySection/IndexCommunityBoardNavBox.tsx
> +        </Text>
저라면
```
type BoardType = 'local' | 'secert' | 'my-step' | 'open-forum'
const boardTitleMap: Record<BoardType, string> = {
  local: '지역별 게시판',
  sercret: '시크릿 게시판',
  ...
}

<Text>{boardTitleMap[type]</Text>
```
정도로 작성할 것 같아요. 긴 한글은 휴먼에러가 발생하기 쉽고, 특정 키워드가 정해져 있는 거라면 string보다는 union을 활용하면 좋을 것 같아요.

2024-10-14 08:59 UTC, danmin20 commented on src/components/CommunitySection/index.tsx
> +        <IndexCommunityBoardNavBox key={board.type} h={283} {...board} />
위와 이어지게, 여기서 사용되는 type은 type보다는 title에 더 가까울 것 같아요.

2024-10-14 08:59 UTC, danmin20 commented on src/components/Survey/QuestionSection.tsx
> +  type?: 'input' | 'select';
밑의 questions를 볼때는 type이 모두 들어가 있는데, 옵셔널로 해주신 이유가 있을까요?

2024-10-14 08:59 UTC, danmin20 commented on src/components/Survey/QuestionSection.tsx
> +}> = ({ index, question }) => {
Props가 동일하다면 더더욱 공통 타입을 정의해주면 좋을 것 같아요~

2024-10-14 09:00 UTC, danmin20 approved these changes

2024-10-14 09:04 UTC, danmin20 commented
저도 실무에서 OAuth를 사용해본 적은 없어서 답변드리기 어려울 것 같은데요~ 실무에서 어떤 방법을 쓰는가보다는 왜 이 방식을 선택했는가를 설명할 수 있게 장단점을 비교해보시면 좋을 것 같아요. 현업에서도 어떤 선택을 할 때, 옳은 선택이란 건 없다고 생각해요. 당시 최선의 선택을 하는 것뿐이라고 생각합니다. 보안상의 이슈는 없는지, 아직 베타 기능인건지 등등을 고려해보시면 좋을 것 같아요.

2024-10-14 09:04 UTC, merged

2024-10-14 17:22 UTC, JaeanHan commented on src/components/CommunitySection/IndexCommunityBoardNavBox.tsx
> +        </Text>
union 타입을 활용해 리팩토링하겠습니다!

2024-10-14 17:23 UTC, JaeanHan commented on src/components/CommunitySection/index.tsx
> +        <IndexCommunityBoardNavBox key={board.type} h={283} {...board} />
title이 용도에 더 직관적인 것 같습니다. 감사합니다!

2024-10-15 11:00 UTC, yunseong0404 commented on src/components/Survey/QuestionSection.tsx
> +  type?: 'input' | 'select';
`src/components/DamagePrevention1/Step1.tsx`의 페이지에서도 SurveyQuestions를 사용하지만 해당 페이지에서는 type을 사용하지 않아 옵셔널로 설정하였습니다!

2024-10-15 11:03 UTC, yunseong0404 commented on src/components/Survey/QuestionSection.tsx
> +  type?: 'input' | 'select';
타입을 페이지별로 따로 생성하는 방법과, 옵셔널로 두어 공통으로 사용하는 방법 중 어떤 방법이 더 좋은 방법인지 궁금합니다!