커뮤니티 댓글,좋아요,타입별보드 조회 api 연동
kakao-tech-campus-2nd-step3/Team11_FE pull request #88
Opened 2024-11-10 08:06 UTC by seongikx

## 📖️ 제목 Week

##### 반영 브랜치 : `seongik -> Week10`
#### 관련 이슈 번호 : `#30`

### 🛠️ 작업 사항
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 세팅 (의존성, 환경 변수, 빌드 관련 코드)

### ️️ 📝 설명
    커뮤니티 댓글,좋아요,타입별보드 조회 api 연동하였습니다.
    추후 검색, 정렬버튼 api 연결 필요합니다.

### 📋 테스트 완료 사항 
    x

### 👨‍💻 리뷰 요구사항
    x

2024-11-10 11:56 UTC, JaeanHan requested changes
리뷰 반영해주시면 머지하겠습니다

2024-11-10 11:56 UTC, JaeanHan commented on .github/workflows/cicd.yml
> +
포매팅은 왜 변경하신 건가요?

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/Comment.tsx
> +        { text: editedText }
api함수들은 api 폴더안에 넣어주세요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/CommentSection.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
useQuery를 사용할 수 있을 거 같아요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/CommentSection.tsx
> +        {isLoading ? (
Suspense를 사용하는게 좋을거 같아요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/PostStats.tsx
>        } catch (error: unknown) {
unknown 타입을 사용하면 안될 것 같아요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/CommentSection.tsx
> +        typeof error.response.data.message === 'string'
중복되는 코드가 많아서 if else 대신 삼항연산자를 쓰는 게 좋을 거 같아요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/utils/api.ts
>    const response = await apiInstance.get(`/api/v1/board/${postId}`);
해당 api가 반환하는 응답객체의 타입을 명시해서 타입을 사용하는게 좋을거 같아요. 비어있으면 항상 빈 배열을 반환하니까요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/utils/api.ts
> +  const actualCommentCount = Array.isArray(
해당 api가 반환하는 응답객체의 타입을 명시해서 타입을 사용하는게 좋을거 같아요. 비어있으면 항상 빈 배열을 반환하니까요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/Comment.tsx
> +      const authToken = localStorage.getItem('Authorization') || '';
apiInstance를 사용하면 자동으로 수행되는 작업입니다

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/Comment.tsx
> +  };
이런 util 함수는 컴포넌트 밖으로 분리해주세요

2024-11-10 11:56 UTC, JaeanHan commented on src/components/ForumPost/CommentSection.tsx
> +    };
api 폴더 내부로 이동시키면 좋겠습니당

2024-11-12 08:45 UTC, closed without merging

2024-11-14 17:23 UTC, seongikx commented on src/components/ForumPost/CommentSection.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
tanstackQuery로 사용할 수 있도록 하겠습니다 !

2024-11-14 17:25 UTC, seongikx commented on src/components/ForumPost/CommentSection.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
tanstackQuery 사용하도록 하겠습니다!